---
title: "Introduction to Data Science with R"
subtitle: "posit::conf(2024)"
format: 
  html:
    toc: true
---

## Welcome

This is not a standard workshop, but a six-week, online Posit Academy apprenticeship followed by a one-day, in-person learning experience at posit::conf(2024).


Here, you will learn the foundations of R for data science together with a close group of fellow learners, under the guidance of a Posit Academy mentor. Topics will include the basics of R, importing data, visualizing and wrangling data with the tidyverse, and reporting reproducibly with Quarto.

**Online Experience (July 1st - August 9th)**

You will be expected to complete a weekly curriculum of interactive tutorials and an applied data science project. You will attend two weekly meetings with your mentor and fellow learners via Zoom to work together, ask questions, and share your work with your group. Visit [posit.co/academy](http://posit.co/academy) to learn more about this uniquely effective learning format.


**In-person experience (August 12th)**

You will join your fellow learners at posit::conf(2024) to practice, apply and extend what you have learned through a series of group coding challenges, led by Posit Academy staff.


**This course is for you if you:**

* are new to R or the tidyverse,
* have dabbled in R, but now want a rigorous foundation in up-to-date data science best practices, or
* are a SAS or Excel user looking to switch your workflows to R.

## Schedule & Slides

| Time          | Activity                                  |
| :------------ | :---------------------------------------- |
| 09:00 - 10:30 | Session 1 - [Welcome](https://intro-tidyverse-2024.netlify.app/_slides/welcome){target="_blank" rel="noopener noreferrer"}, [Warm-up](https://intro-tidyverse-2024.netlify.app/_slides/warm-up){target="_blank" rel="noopener noreferrer"} & [Data types](https://intro-tidyverse-2024.netlify.app/_slides/data-types){target="_blank" rel="noopener noreferrer"} |
| 10:30 - 11:00 | *Coffee break*                            |
| 11:00 - 12:30 | Session 2 - [Exploratory data analysis](https://github.com/posit-conf-2024/intro-ds-r/blob/main/slides/eda.pdf){target="_blank" rel="noopener noreferrer"}     |
| 12:30 - 13:30 | *Lunch break*                             |
| 13:30 - 15:00 | Session 3 - [Explore new data](https://intro-tidyverse-2024.netlify.app/_slides/explore-new-data#1){target="_blank" rel="noopener noreferrer"}              |
| 15:00 - 15:30 | *Coffee break*                            |
| 15:30 - 17:00 | Session 4 - [Share and Wrap-up](https://intro-tidyverse-2024.netlify.app/_slides/wrap-up#1){target="_blank" rel="noopener noreferrer"}             |

## Logistics

### WiFi

* Network: **Posit Conf 2024**
* Password: **conf2024**

### Important locations

* **This workshop**: 502 (Cowlitz)
* There are **gender-neutral bathrooms** located on Levels 3, 4, 5, 6 & 7
* There is a **meditation/prayer room** is located in 503 and a **lactation room** in 509. Both are available Mon & Tues 7am - 7pm, and Wed 7am - 5pm.

### Photography policy

Participants who do not wish to be photographed have red lanyards; please note everyone’s lanyard colors before taking a photo and respect their choices.

## Code of Conduct

The Code of Conduct can be found at [https://posit.co/code-of-conduct](https://posit.co/code-of-conduct/). Please review them carefully. You can report Code of Conduct violations in person, by email, or by phone. Please see the policy linked above for contact information.